#+BEGIN_EXPORT html
---
title: Convert automatically pgf/tikz files to pdf/png
date: 2021-02-23
permalink: /posts/2021/02/Convert-automatically-pgf-tikz-files-to-pdf
tags:
  - bash
  - python
  - latex
---
#+END_EXPORT
#+OPTIONS: toc:nil
#+OPTIONS: num:nil

When writing my dissertation, I tried to generate my figures in the
most coherent way possible. I used a matplotlib stylesheet, and
exported all my figures to pgf (TikZ is built on top of pgf, as LaTeX
is built on top of TeX). For simple figures, everything was fine:
vectorized figures, nice integration with LaTeX. However, for more
complicated figures, such as contourf or geographical maps, the pgf
files became very large (more than 5Mb). Instead of regenerating those
files from the code (which maybe I should have done in the first
place), I wrote this bash script in order to convert chosen figures in
png, with enough dpi (Dots Per Inche). This create a =.tex= file, with
only the figure. Once compiled, the output is converted using imagick
and its =convert= command. Finally, we remove the auxiliary files
created in the process. There probably exist better ways to do this.

Put this in =convert_pgf_to_png=
#+begin_src bash
filename=${1%.pgf}
echo $filename
echo "\documentclass[preview,border=4mm]{standalone}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{url}
\usepackage{tikz}
\usepackage{color}
\usepackage{xcolor}
\begin{document}" > tmp.tex
echo "\input{"$1"}" >> tmp.tex
echo "\end{document}" >> tmp.tex

pdflatex tmp.tex > cvert.log

convert -density 500 -units pixelsperinch tmp.pdf $filename.png
rm -f tmp.tex tmp.aux tmp.pdf tmp.log tmp.fls tmp.fdb_latexmk tmp.ps tmp.dvi
#+end_src

=chmod +x convert_pgf_to_png= to be able to execute it, and you can then
#+begin_src bash
  convert_pgf_to_png filename
#+end_src

This is based on a stackoverflow answer I found somewhere.
